version: '3'
services:
  db:
    image: "mysql:5.7"
    container_name: uvdesk_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: "m3d1am3ter"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "m3d1am3ter"
    networks:
      - proxy
  uvdesk:
    image: nuttcorp/uvdesk:latest
    depends_on:
      - db
    tty: true
    environment:
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "m3d1am3ter"
        MYSQL_ROOT_PASSWORD: "m3d1am3ter"
        MYSQL_DATABASE: uvdesk
    ports:
        - 8088:80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uvdesk.rule=Host(`uvdesk.local`)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    networks:
      - proxy
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_PASSWORD: "m3d1am3ter"
      # PMA_ARBITRARY: 1

volumes:
  db_data: {}

networks:
  proxy:
    external: true